name: Latest blog post workflow
on:
  schedule:
    # every 4 hours
    - cron: "0 */4 * * *"

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.ieni.dev/posts/index.xml"
