name: Latest YouTube Videos
on:
  schedule:
    # every 4 hours
    - cron: "0 */4 * * *"

jobs:
  update-readme-with-youtube:
    name: Get latest youtube videos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCLGEzEK13QxWvKNRCFeF6QQ"
